link_libraries("F:/opencv/sources/include")
link_libraries("F:/opencv/sources/include/opencv2")


LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_calib3d455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_core455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_dnn455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_features2d455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_flann455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_gapi455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_highgui455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_imgcodecs455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_imgproc455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_ml455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_objdetect455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_photo455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_stitching455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_ts455.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_video455.dll.a")
LINK_LIBRARIES("F:/opencv/cbuild/lib/libopencv_videoio455.dll.a")
